// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0cmyl9U0q1YP3kI9YDrShZZAnHBgWy6w',
    appId: '1:783709943066:web:48bbaaaa54284f7cf268a3',
    messagingSenderId: '783709943066',
    projectId: 'firenote327',
    authDomain: 'firenote327.firebaseapp.com',
    storageBucket: 'firenote327.firebasestorage.app',
    measurementId: 'G-E76TM11XLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1otqATSXnkN4dCXPszsZqle0uDL3qSuE',
    appId: '1:783709943066:android:17ea6a0445c1bd12f268a3',
    messagingSenderId: '783709943066',
    projectId: 'firenote327',
    storageBucket: 'firenote327.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJgYBw-Y5jhQbO98KGfLw2pCMK9fVIgAY',
    appId: '1:783709943066:ios:e9c820978662c521f268a3',
    messagingSenderId: '783709943066',
    projectId: 'firenote327',
    storageBucket: 'firenote327.firebasestorage.app',
    iosBundleId: 'com.example.fireNote327',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJgYBw-Y5jhQbO98KGfLw2pCMK9fVIgAY',
    appId: '1:783709943066:ios:e9c820978662c521f268a3',
    messagingSenderId: '783709943066',
    projectId: 'firenote327',
    storageBucket: 'firenote327.firebasestorage.app',
    iosBundleId: 'com.example.fireNote327',
  );
}
